Rename Vector Tile source functions and Add GEOJSON attribute to trip
themobilitybox/mobilitybox-js pull request #5
Opened 2021-03-09 12:21 UTC by TimVesputi

2021-03-09 12:22 UTC, TimVesputi commented
TODO: create issue to remove deprecated versions of methods in version 4.0

2021-03-12 09:16 UTC, rosario-raulin requested changes
Please fix the documentation issues that I mentioned and then we can merge that.

2021-03-12 09:16 UTC, rosario-raulin commented on README.md
> +In order to show a transit map with paths for different routes on a map it is usefull to transfer them as map tiles. (Gives you only the currently displayed segments.)
We should explain what the transit map layer is, for instance:

> The transit map layer is a set of lines on a map which represent the typical routes public transit vehicles take. This includes for example buses, trams and subways. This transit map layer might show routes of different importance on different zoom levels.

2021-03-12 09:16 UTC, rosario-raulin commented on src/index.js
> +   * @param {object} origins_from_station MobilityboxStop or Identifier of the first station of the trip. Usually the start with: `vesputi:station:`
> Usually the start with: `vesputi:station:`

Usually *they* start with? This is typo. The same for the following parameters.

2021-03-12 09:16 UTC, rosario-raulin commented on src/index.js
> +   * @param {object} origins_from_departure_time The departure time on the starting station as unix timestamp in milliseconds or as MobilityboxEventTime
We should not switch between "origin station" and "start station". By the way: A "starting station" is a strange phrase. Better:

> The departure time of the origin station as a unix timestamp in milliseconds or a MobilityboxEventTime object

2021-03-12 09:16 UTC, rosario-raulin commented on src/index.js
> +   * @param {object} destination_arrival_time The arrival time on the ending station as unix timestamp in milliseconds or as MobilityboxEventTime
See above. "Ending station" is not a phrase we should use. The right term is "destination station".

2021-03-12 09:16 UTC, rosario-raulin commented on src/index.js
> +   * @return {MobilityboxTrip} found trip
The return value is a promise, right? Not the MobilityboxTrip directly. That's confusing then for the user of this API.

2021-03-12 09:16 UTC, rosario-raulin commented on README.md
> +returns with a *MobilityboxTrip* object based on its meta information.
Actually it returns a promise that in turn returns a MobilityboxTrip object. We should clarify that.

2021-03-12 10:16 UTC, rosario-raulin approved these changes

2021-03-12 10:16 UTC, merged

2021-03-12 10:17 UTC, renemeye commented
:tada: This PR is included in version 3.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/mobilitybox/v/3.2.0)
- [GitHub release](https://github.com/themobilitybox/mobilitybox-js/releases/tag/v3.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: